In [5]:
import numpy as np
a=np.empty((2,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
a=np.array([1,2,3,4,5])
print(a[2]+a[4])

8


In [15]:
a=np.array([[1,2,3,4],[6,7,8,9]])
print(a)
print(a[1,3])


[[1 2 3 4]
 [6 7 8 9]]
9


In [24]:
a=np.array([[[1,2,3,4],[6,7,8,9]],[[11,12,13,14],[21,22,23,24]]])
print(a[1,1,-2])

23


In [37]:
a=np.array([2,3,4,5,6,7,8])
print(a[-2:-1])  #start index is included and end index is excluded 

[7]


In [52]:
a=np.array([[2,9,4,5,6,7,8],[12,13,14,15,16,17,18]])
print(a[0:2,1:4])
print("shape:",a.shape)

[[ 9  4  5]
 [13 14 15]]
shape: (2, 7)


In [55]:
a=np.zeros((3,4,5))
print(a)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [61]:
a=np.full((2,2,3), 7)
print(a)

[[[7 7 7]
  [7 7 7]]

 [[7 7 7]
  [7 7 7]]]


In [67]:
a = np.array([1, 2, 3, 4, 5])
x = a.view()
print(x)
a[0] = 10
print(a)
print(x)


[1 2 3 4 5]
[10  2  3  4  5]
[10  2  3  4  5]


In [77]:
arr=np.array([1,2,3,4,5,6,7,8])
print(arr.reshape(2,4))


[[1 2 3 4]
 [5 6 7 8]]


In [78]:
arr=np.array([[1,2,3,4],
              [5,6,7,8]])
print(arr.shape)


(2, 4)
