In [1]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([[4,5,6],[7,8,9]])
print(np.vstack((arr1,arr2)))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr=np.array([[1,2,3],[6.,7,8]])
res=arr.flatten()
print(res)

[1. 2. 3. 6. 7. 8.]


In [7]:
arr1=np.array([1,2,3])
print(arr1[::-1]) 


[3 2 1]


In [22]:
arr=np.array([10,4,87,91,56,22])
print(np.max(arr))
print(np.min(arr))
arr1 = np.array([
    [1, 2, 3],
    [4, 5, 6]])
print(arr1.shape)
print(arr1[1,2])

91
4
(2, 3)
6


In [26]:
arr1 = np.array([
    [1, 2, 3],
    [4, 5, 6]])
total = 0

for row in arr1:
    for value in row:
        total+=value
print(total)

21


In [27]:
import numpy as np

a=np.array([[1,2,3],[4,5,7]])
b=np.array([[7,8,9],[10,11,12]])
print(a+b) 
print(a-b)
print(a*b)
print(a/b)
print(a**b)

[[ 8 10 12]
 [14 16 19]]
[[-6 -6 -6]
 [-6 -6 -5]]
[[ 7 16 27]
 [40 55 84]]
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.58333333]]
[[          1         256       19683]
 [    1048576    48828125 13841287201]]


In [41]:
arr=np.array([[[1,2,3],[4,5,6]],
             [[7,8,9],[10,11,12]]]) 
for block in arr:
    for row in block:
        for value in row:
            print(value,end=' ') 
 
for x in np.nditer(arr):
    print(x)

1 2 3 4 5 6 7 8 9 10 11 12 1
2
3
4
5
6
7
8
9
10
11
12


In [53]:
import numpy as np
from statistics import mode

arr1 = np.array([
    [10, 20],
    [30, 40]
])

arr2 = np.array([
    [50, 60],
    [70, 80]
])

avg=(arr1+arr2)/2
print(avg)

res=np.concatenate((arr1.flatten(),arr2.flatten()))
print(res)
print(np.mean(res))
print(mode(res))
print(np.median(res))

[[30. 40.]
 [50. 60.]]
[10 20 30 40 50 60 70 80]
45.0
10
45.0
