In [4]:
import numpy as np
a=np.array([[1,2,3],[7,4,9]])
print(a)
res=np.transpose(a)
print(res)


[[1 2 3]
 [7 4 9]]
[[1 7]
 [2 4]
 [3 9]]


In [15]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])
res=np.concatenate((arr1,arr2),axis=0) 
print(res)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [19]:
arr=np.arange(9)
print(arr)
res=np.split(arr,3)
print(res)

[0 1 2 3 4 5 6 7 8]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [29]:
arr=np.array([[1,2,3],[7,4,9]])
print(arr)
b=np.resize(arr,(3,2)) 
print(b)



[[1 2 3]
 [7 4 9]]
[[1 2]
 [3 7]
 [4 9]]


In [39]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(np.append(arr,[[7,8,9]],axis=0))
print(np.append(arr,[[7,8,9],[10,11,12]],axis=1))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [44]:
arr=np.array([[1,2],[3,4],[7,8],[9,10]])
print(arr)
a=np.insert(arr,2,[5,6],axis=0)
print(a)

[[ 1  2]
 [ 3  4]
 [ 7  8]
 [ 9 10]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [ ]:
arr=np.array([1,2,3,4,5])
res=np.flip(arr) 
print(res)

[5 4 3 2 1]


In [50]:
arr=np.array([5,3,4,2,8,7,1])
arr=np.sort(arr)
print(arr)

[1 2 3 4 5 7 8]


In [52]:
arr=np.array([5,3,4,2,8,7,1])
arr=np.argmin(arr)
print(arr)

6


In [56]:
#indexing and slicing

arr=np.arange(10)
b=arr[6]
print(b)

6


In [57]:
a=np.array(
    [
        [[123,4,5],[2,3,4]],
        [[123,4,5,],[2,3,4]]
    ]
) 
print(a)

[[[123   4   5]
  [  2   3   4]]

 [[123   4   5]
  [  2   3   4]]]


In [4]:
import numpy as np

a=np.array([[1,2,3],[4,5,7]])
b=np.array([[7,8,9],[10,11,12]])
print(a+b) 
print(a-b)
print(a*b)
print(a/b)
print(a**b)

[[ 8 10 12]
 [14 16 19]]
[[-6 -6 -6]
 [-6 -6 -5]]
[[ 7 16 27]
 [40 55 84]]
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.58333333]]
[[          1         256       19683]
 [    1048576    48828125 13841287201]]


In [8]:
b=np.array([[7,8,9],[10,11,12]])
res=np.sum(b,axis=1)
print(b)
print(res)

[[ 7  8  9]
 [10 11 12]]
[24 33]


In [13]:
a=np.array([[7,8,9],[10,11,12]])
res=np.mean(a,axis=0)
print(res)  


[ 8.5  9.5 10.5]
