In [7]:
import numpy as np
arr1=np.array([[1,2,3,4],[5,6,7,8]])
print(arr1.reshape(4,2))
print(arr1.shape) 
print(arr1.ndim)
print(arr1.dtype)
print(arr1.itemsize)
  

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(2, 4)
2
int64
8


In [9]:
arr=np.full((3,3),9)
print(arr)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [11]:
arr=np.linspace(25,125,10)
print(arr)

[ 25.          36.11111111  47.22222222  58.33333333  69.44444444
  80.55555556  91.66666667 102.77777778 113.88888889 125.        ]


In [14]:
lst=[10,20,30,40]
sdv=np.array(lst)
print(sdv)

[10 20 30 40]


In [16]:
arr=np.array([123,532,631,190,232,111])
print(arr[::-1])

[111 232 190 631 532 123]


In [25]:
arr=np.arange(48).reshape(4,4,3)
print(arr)
val=arr[3,2,2]
print(val)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]]]
44


In [37]:
import numpy as np
arr=np.arange(1,17).reshape(4,4)
print(arr) 
res=arr[1::2,::2]
print(res)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 5  7]
 [13 15]]
