In [4]:
import numpy as np
a=np.array([
    [1,2,3,4,5],
    [np.nan,22,35,43,51]
    ])
print(a,type(a))

[[ 1.  2.  3.  4.  5.]
 [nan 22. 35. 43. 51.]] <class 'numpy.ndarray'>


In [5]:
arr=np.nan_to_num(a,nan=0) 
print(arr)

[[ 1.  2.  3.  4.  5.]
 [ 0. 22. 35. 43. 51.]]


In [6]:
a_transpose=arr.T
print(a_transpose) 

[[ 1.  0.]
 [ 2. 22.]
 [ 3. 35.]
 [ 4. 43.]
 [ 5. 51.]]


In [7]:
import numpy as np

arr = np.arange(24).reshape(2, 3, 4)

print("Original Shape:", arr.shape)

# move axes
new_arr = np.moveaxis(arr, 0, 2)

print("\nNew Shape:", new_arr.shape)

print("\nNew Array:\n", new_arr)

Original Shape: (2, 3, 4)

New Shape: (3, 4, 2)

New Array:
 [[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]


In [18]:
import numpy as np
arr=np.array([
    [1,2,np.nan],
    [4,np.nan,45],
    [7,8,9]
])
print(arr)
col_mean=np.nanmean(arr,axis=0)
print("average of colums",col_mean)
ind=np.where(np.isnan(arr))
print(ind)
arr[ind] = np.take(col_mean, ind[1])
print(arr)

[[ 1.  2. nan]
 [ 4. nan 45.]
 [ 7.  8.  9.]]
average of colums [ 4.  5. 27.]
(array([0, 1]), array([2, 1]))
[[ 1.  2. 27.]
 [ 4.  5. 45.]
 [ 7.  8.  9.]]


In [20]:
arr=np.array([2,-2.-3,8,-1,-6,9])
print(arr)
arr[arr<0]=0
print(arr)


[ 2. -5.  8. -1. -6.  9.]
[2. 0. 8. 0. 0. 9.]
