In [6]:
import pandas as pd 
df = pd.read_csv('tips.csv')
res=df.groupby('day')['total_bill'].sum()  
print(res)  


day
Fri      325.88
Sat     1778.40
Sun     1627.16
Thur    1096.33
Name: total_bill, dtype: float64


In [57]:
import pandas as pd 
df = pd.read_csv('tips.csv') 
print(df.to_string)


<bound method DataFrame.to_string of      total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]>


In [8]:
import pandas as pd 
df = pd.read_csv('tips.csv')
print(pd.options.display.max_rows)

60


In [12]:
print(df.tail(10))

     total_bill   tip     sex smoker   day    time  size
234       15.53  3.00    Male    Yes   Sat  Dinner     2
235       10.07  1.25    Male     No   Sat  Dinner     2
236       12.60  1.00    Male    Yes   Sat  Dinner     2
237       32.83  1.17    Male    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2


In [13]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    str    
 3   smoker      244 non-null    str    
 4   day         244 non-null    str    
 5   time        244 non-null    str    
 6   size        244 non-null    int64  
dtypes: float64(2), int64(1), str(4)
memory usage: 13.5 KB
None


In [15]:
print(df.shape)

(244, 7)


In [21]:
print(df['tip'])


0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64


In [25]:
print(df[df['total_bill']>25])


     total_bill    tip     sex smoker   day    time  size
5         25.29   4.71    Male     No   Sun  Dinner     4
7         26.88   3.12    Male     No   Sun  Dinner     4
11        35.26   5.00  Female     No   Sun  Dinner     4
23        39.42   7.58    Male     No   Sat  Dinner     4
39        31.27   5.00    Male     No   Sat  Dinner     3
44        30.40   5.60    Male     No   Sun  Dinner     4
47        32.40   6.00    Male     No   Sun  Dinner     4
48        28.55   2.05    Male     No   Sun  Dinner     3
52        34.81   5.20  Female     No   Sun  Dinner     4
54        25.56   4.34    Male     No   Sun  Dinner     4
56        38.01   3.00    Male    Yes   Sat  Dinner     4
57        26.41   1.50  Female     No   Sat  Dinner     2
59        48.27   6.73    Male     No   Sat  Dinner     4
72        26.86   3.14  Female    Yes   Sat  Dinner     2
73        25.28   5.00  Female    Yes   Sat  Dinner     2
77        27.20   4.00    Male     No  Thur   Lunch     4
83        32.6

In [28]:
print(df['total_bill'].value_counts())

total_bill
13.42    3
10.34    2
21.01    2
10.33    2
17.92    2
        ..
29.03    1
27.18    1
22.67    1
17.82    1
18.78    1
Name: count, Length: 229, dtype: int64


In [31]:
import pandas as pd
df=pd.read_json('airports.json')
print(df)

                                             airports
0   {'code': 'ATL', 'name': 'Hartsfield-Jackson At...
1   {'code': 'PEK', 'name': 'Beijing Capital Inter...
2   {'code': 'DXB', 'name': 'Dubai International',...
3   {'code': 'LAX', 'name': 'Los Angeles Internati...
4   {'code': 'HND', 'name': 'Tokyo Haneda', 'city'...
5   {'code': 'ORD', 'name': 'O'Hare International'...
6   {'code': 'LHR', 'name': 'London Heathrow', 'ci...
7   {'code': 'PVG', 'name': 'Shanghai Pudong Inter...
8   {'code': 'CDG', 'name': 'Paris Charles de Gaul...
9   {'code': 'DFW', 'name': 'Dallas/Fort Worth Int...
10  {'code': 'CAN', 'name': 'Guangzhou Baiyun Inte...
11  {'code': 'AMS', 'name': 'Amsterdam Schiphol', ...
12  {'code': 'FRA', 'name': 'Frankfurt Airport', '...
13  {'code': 'IST', 'name': 'Istanbul Airport', 'c...
14  {'code': 'SIN', 'name': 'Singapore Changi', 'c...
15  {'code': 'ICN', 'name': 'Incheon International...
16  {'code': 'DEN', 'name': 'Denver International'...
17  {'code': 'BKK', 'name': 

In [33]:
print(df.shape)

(30, 1)


In [55]:
df=pd.read_csv('tips1.csv')
print(df.to_string())

     total_bill    tip     sex smoker   day    time  size
0           NaN   1.01  Female     No   Sun  Dinner     2
1           NaN   1.66    Male     No   Sun  Dinner     3
2           NaN   3.50    Male     No   Sun  Dinner     3
3         23.68   3.31    Male     No   Sun  Dinner     2
4         24.59   3.61  Female     No   Sun  Dinner     4
5         25.29   4.71    Male     No   Sun  Dinner     4
6          8.77   2.00    Male     No   Sun  Dinner     2
7         26.88   3.12    Male     No   Sun  Dinner     4
8         15.04   1.96    Male     No   Sun  Dinner     2
9         14.78   3.23    Male     No   Sun  Dinner     2
10        10.27   1.71    Male     No   Sun  Dinner     2
11        35.26   5.00  Female     No   Sun  Dinner     4
12        15.42   1.57    Male     No   Sun  Dinner     2
13        18.43   3.00    Male     No   Sun  Dinner     4
14        14.83   3.02  Female     No   Sun  Dinner     2
15        21.58   3.92    Male     No   Sun  Dinner     2
16        10.3

In [36]:
res=df.dropna()
print(res)

     total_bill   tip     sex smoker   day    time  size
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
5         25.29  4.71    Male     No   Sun  Dinner     4
6          8.77  2.00    Male     No   Sun  Dinner     2
7         26.88  3.12    Male     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[241 rows x 7 columns]


In [41]:
print(df.dropna)
print(df.shape)

<bound method DataFrame.dropna of      total_bill   tip     sex smoker   day    time  size
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
5         25.29  4.71    Male     No   Sun  Dinner     4
6          8.77  2.00    Male     No   Sun  Dinner     2
7         26.88  3.12    Male     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[241 rows x 7 columns]>
(241, 7)


In [58]:
import pandas as pd
df=pd.read_csv("tips1.csv")
print(df.to_string)
print(df.fillna(120))

<bound method DataFrame.to_string of      total_bill   tip     sex smoker   day    time  size
0           NaN  1.01  Female     No   Sun  Dinner     2
1           NaN  1.66    Male     No   Sun  Dinner     3
2           NaN  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]>
     total_bill   tip     sex smoker   day    time  size
0        120.00  1.01  Female     No   Sun  Dinner     2
1        120.00  1.66    Male     No   Sun  Dinner     3
2        120.00  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    M

In [90]:
df1=pd.read_csv('tips1.csv')
print(df1.to_string)

<bound method DataFrame.to_string of      total_bill   tip     sex smoker   day    time  size
0           NaN  1.01  Female     No   Sun  Dinner     2
1           NaN  1.66    Male     No   Sun  Dinner     3
2           NaN  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]>


In [64]:
#numpy
import numpy as np
print(np.__version__)
a=np.array([
    [1,2,3,4,5],
    [11,22,35,43,51]
    ])
print(a,type(a),a.dtype)

2.4.6
[[ 1  2  3  4  5]
 [11 22 35 43 51]] <class 'numpy.ndarray'> int64


In [71]:
a=np.array([
    'A','B','C'
])
print(a,type(a),a.dtype)

['A' 'B' 'C'] <class 'numpy.ndarray'> <U1


In [77]:
a=np.ones((5,2,5))
print(a)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [86]:
a=np.ones((6,3),order='F')
print(a)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
